### ISSUE TITLE
Event handlers firing twice

### ISSUE THREAD

**Issue by kevinresol** [JustFly1984/react-google-maps-api#79]
With the following code the onRectangleComplete callback is fired twice. This also happens on other onComplete callbacks too.

```jsx
<DrawingManager
	options={{
		drawingControlOptions: {
			drawingModes: [
				google.maps.drawing.OverlayType.RECTANGLE,
			]
		}
	}}
	onRectangleComplete={rect => {
		console.log('onRectangleComplete');
	}}
/>
```

## Environment

os: mac

node --version = v8.15.1

react version = 16.8.6

webpack version = 4.8.3

@babel version = 7.4.3

@react-google-maps/api version = 1.2.0-alpha.11

## How is it behave?

`onRectangleComplete` will be printed twice after drawing a rectangle.

## How should it behave correctly?

`onRectangleComplete` should only be printed once

**Comment by uriklar** [comment]
@kevinresol Thanks for this huge bug report! This wasn't even related to DrawingManager, but to each and every event callback. Opened a PR that should be released as 1.2.0-alpha.12 later today

**Comment by uriklar** [comment]
@kevinresol Fixed in 1.2.0-alpha.14

**Comment by cuongdevjs** [comment]
event onChangeCenter or onBoundChange also fire twice. Have you fixed this problem?

**Comment by JustFly1984** [comment]
@uriklar

**Comment by MattL-NZ** [comment]
@JustFly1984 I think this one needs to be reopened as the issue is still happening with `DrawingManagerF`
Can be replicated with the below.

```
<DrawingManagerF
  onCircleComplete={value => console.log(value)}
  options={{
      drawingMode: google.maps.drawing.OverlayType.CIRCLE,
      drawingControlOptions: {
        position: google.maps.ControlPosition.TOP_RIGHT,
      }
    }}
/>
```
